name: Core Web Vitals Check

on: [workflow_dispatch]

jobs:
  core-web-vitals-check:
    runs-on: ubuntu-latest
    steps:
      - name: Run Lighthouse
        run: |
          npm install -g lighthouse
          lighthouse ${{ env.WEBSITE_URL }} --output=json --output-path=./vitals_report.json --chrome-flags="--headless"

      - name: Upload Report
        uses: actions/upload-artifact@v7
        with:
          name: lighthouse-report
          path: ./vitals_report.json
